version: '3.1'
services:
  exporter:
    image: 'joshi425/minecraft_exporter'
    environment:
      - RCON_HOST=
      - RCON_PORT=
      - RCON_PASSWORD=
      - FORGE_SERVER=
    volumes:
      - /srv/minecraft/data/world:/world
    ports:
      - 8000:8000
    depends_on:
      - server
  prometheus:
    image: 'prom/prometheus'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - exporter
  server:
    image: 'itzg/minecraft-server'
    environment:
      - MEMORY=
      - VERSION=
      - TYPE=
      - FORGEVERSION=
      - EULA=TRUE
      - FORCE_REDOWNLOAD=
    ports:
      - 25565:25565
      - 25575:25575
    volumes:
      - /srv/minecraft/data:/data
